import React, { useState } from 'react';
import { 
  Sparkles, 
  Lightbulb, 
  HelpCircle, 
  Wrench, 
  Clock, 
  AlertTriangle, 
  RotateCw,
  CheckCircle,
  Info
} from 'lucide-react';

export default function AiAnalysisSection({ log, onAnalyze, analyzing, error }) {
  const isAnomaly = Boolean(log.isAnomaly);
  const hasAiAnalysis = Boolean(log.aiExplanation);

  // Case 1: Normal Log
  if (!isAnomaly) {
    return (
      <div className="ai-section-box ai-section-normal">
        <div className="ai-normal-header">
          <Info size={18} color="#06b6d4" />
          <span style={{ fontWeight: 600, color: '#e2e8f0' }}>AI Root Cause Analysis Inactive</span>
        </div>
        <p className="ai-normal-desc">
          This log is classified as <strong>Normal</strong> (Score: {log.anomalyScore}/100). In accordance with assessment architecture rules, Gemini AI is only engaged for anomalous events requiring technical triage.
        </p>
      </div>
    );
  }

  // Case 2: Anomaly Already Analyzed
  if (hasAiAnalysis) {
    return (
      <div className="ai-section-box ai-section-analyzed">
        <div className="ai-analyzed-header">
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <div className="ai-sparkle-badge">
              <Sparkles size={16} color="#8b5cf6" />
            </div>
            <div>
              <h4 style={{ fontSize: '1rem', fontWeight: 600, color: '#f8fafc' }}>
                Gemini AI Root Cause Explanation
              </h4>
              <span style={{ fontSize: '0.75rem', color: '#94a3b8' }}>
                Generated by server-side Gemini AI model
              </span>
            </div>
          </div>
          <button
            className="btn btn-ghost"
            onClick={() => onAnalyze(log.id)}
            disabled={analyzing}
            title="Re-run Gemini AI analysis"
            style={{ fontSize: '0.75rem', padding: '0.35rem 0.75rem' }}
          >
            <RotateCw size={13} className={analyzing ? 'spin' : ''} />
            <span>{analyzing ? 'Re-analyzing...' : 'Re-Analyze'}</span>
          </button>
        </div>

        {error && (
          <div className="ai-error-banner">
            <AlertTriangle size={16} />
            <span>{error}</span>
          </div>
        )}

        <div className="ai-cards-stack">
          {/* 1. Plain English Explanation */}
          <div className="ai-card ai-card-explanation">
            <div className="ai-card-title">
              <Lightbulb size={16} color="#fbbf24" />
              <span>Plain-English Summary</span>
            </div>
            <p className="ai-card-content">{log.aiExplanation}</p>
          </div>

          {/* 2. Likely Root Cause */}
          <div className="ai-card ai-card-rootcause">
            <div className="ai-card-title">
              <HelpCircle size={16} color="#f87171" />
              <span>Likely Technical Root Cause</span>
            </div>
            <p className="ai-card-content">{log.aiRootCause}</p>
          </div>

          {/* 3. Recommended Next Step */}
          <div className="ai-card ai-card-nextstep">
            <div className="ai-card-title">
              <Wrench size={16} color="#34d399" />
              <span>Recommended Actionable Next Step</span>
            </div>
            <p className="ai-card-content">{log.aiNextStep}</p>
          </div>
        </div>

        {log.aiGeneratedAt && (
          <div className="ai-meta-footer">
            <Clock size={13} />
            <span>Analyzed at: {new Date(log.aiGeneratedAt).toLocaleString()}</span>
          </div>
        )}
      </div>
    );
  }

  // Case 3: Anomaly Needs AI Analysis
  return (
    <div className="ai-section-box ai-section-pending">
      <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '12px' }}>
        <div className="ai-sparkle-badge" style={{ background: 'rgba(139, 92, 246, 0.2)' }}>
          <Sparkles size={20} color="#a78bfa" />
        </div>
        <div>
          <h4 style={{ fontSize: '1rem', fontWeight: 600, color: '#f8fafc' }}>
            Gemini AI Root Cause Analysis Available
          </h4>
          <p style={{ fontSize: '0.8rem', color: '#94a3b8', margin: 0 }}>
            This detected anomaly has not been analyzed yet. Request on-demand explanation from Gemini AI.
          </p>
        </div>
      </div>

      {error && (
        <div className="ai-error-banner" style={{ marginBottom: '12px' }}>
          <AlertTriangle size={16} />
          <span>{error}</span>
        </div>
      )}

      <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginTop: '12px' }}>
        <button
          className="btn btn-primary"
          onClick={() => onAnalyze(log.id)}
          disabled={analyzing}
          style={{ background: 'linear-gradient(135deg, #8b5cf6, #6366f1)' }}
        >
          <Sparkles size={16} className={analyzing ? 'spin' : ''} />
          <span>{analyzing ? 'Consulting Gemini AI...' : 'Analyze with Gemini AI'}</span>
        </button>

        {analyzing && (
          <span style={{ fontSize: '0.8rem', color: '#a78bfa' }}>
            Generating technical diagnosis and next steps...
          </span>
        )}
      </div>
    </div>
  );
}
